---
title: "Exposure to Generative AI Across Educational Fields in the EU"
author: 
    - Andrea Blasco^[European Commission, Joint Research Centre, andrea.blasco@ec.europa.eu]
    - Claudio Costanzo^[ECARES, European Commission, Joint Research Centre]

date: "This version: `r format(Sys.Date(), '%b %d, %Y')`"

papersize: a4
geometry: "margin=.5in"
fontsize: 12pt
mainfont: Helvetica

linestretch: 1.15

colorlinks: yes
link-citations: yes
linkcolor: blue
citecolor: blue
urlcolor: blue

bibliography: "`r here::here('refs.bib')`"

csl: [https://www.zotero.org/styles/education-economics]

header-includes: |
    ```{=latex}
    %\usepackage{endfloat}
    \usepackage{microtype}         % Better typographic spacing
    \usepackage{parskip}
    \setlength{\parindent}{0pt}    % Removes paragraph indentation
    ```
---

```{r setup, include = FALSE}
library(dplyr)
library(ggplot2)
library(kableExtra)

is_pdf <- knitr::is_latex_output()
knitr::opts_chunk$set(
    error = TRUE,
    echo = FALSE,
    dev = ifelse(is_pdf, "pdf", "png")
)
```

```{r sections, child = c("01_intro.Rmd", "02_methods.Rmd", "03_results.Rmd", "04_discussion.Rmd")}
```
