
recode_isced_field <- function(field) {
    dplyr::case_match(
        field,
        "Basic programmes and qualifications" ~ "001",
        "Literacy and numeracy" ~ "002",
        "Personal skills and development" ~ "003",
        "Education" ~ "011",
        "Arts" ~ "021",
        "Humanities (except languages)" ~ "022",
        "Languages" ~ "023",
        "Social and behavioural sciences" ~ "031",
        "Journalism and information" ~ "032",
        "Business and administration" ~ "041",
        "Law" ~ "042",
        "Biological and related sciences" ~ "051",
        "Environment" ~ "052",
        "Physical sciences" ~ "053",
        "Mathematics and statistics" ~ "054",
        "Information and Communication Technologies (ICTs)" ~ "061",
        "Engineering and engineering trades" ~ "071",
        "Manufacturing and processing" ~ "072",
        "Architecture and construction" ~ "073",
        "Agriculture" ~ "081",
        "Forestry" ~ "082",
        "Fisheries" ~ "083",
        "Veterinary" ~ "084",
        "Health" ~ "091",
        "Welfare" ~ "092",
        "Personal services" ~ "101",
        "Hygiene and occupational health services" ~ "102",
        "Security services" ~ "103",
        "Transport services" ~ "104",
        "Don’t know" ~ "997",
        "No answer" ~ "998",
        "NA" ~ "999",
        .default = NA_character_
    )
}